name: BanItem
author: LDX
authors: [ねらひかだ]
version: 2.2.12
api: [3.0.0, 3.0.0-ALHPA7, 3.0.0-ALHPA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
main: LDX\BanItem\Main
load: POSTWORLD
website: https://github.com/LDX-MCPE/BanItem
commands:
  banitem:
    description: "BanItem main command."
    permission: banitem.command.banitem
    usage: "/banitem <ban/unban/list> [ID[:Damage]]"
permissions:
  banitem:
    default: false
    description: "Allows access to all BanItem features."
    children:
      banitem.bypass:
        default: false
        description: "Allows access to using banned items."
      banitem.command:
        default: false
        description: "Allows access to all BanItem commands."
        children:
          banitem.command.banitem:
            default: op
            description: "Allows access to the item command."